set-window-option -g mode-keys vi
setw -g aggressive-resize on
set-option -g detach-on-destroy off
# Enable the terminal title update
set-option -g set-titles on

# Set the title format to "tmux: session:window"
set-option -g set-titles-string "tmux: #S:#W"
